try {
    hello();
} catch (error) {
    console.log(error);
}

const hi = () => console.log('Hello World');
try {
    hi();
} catch (error) {
    console.log(error);
}